In [4]:
import pandas as pd
a=["ashritha","paavani"," srujitha","madhuri","harshitha","jaya","ashlesha"]
r=pd.Series(a,index=[67,43,44,89,34,45,23])
print(r)

67     ashritha
43      paavani
44     srujitha
89      madhuri
34    harshitha
45         jaya
23     ashlesha
dtype: object

In [5]:
df=pd.read_csv("/content/diabetcsv.csv")
print(df)

     preg  plas  pres  skin  insu  mass   pedi  age            class
0       6   148    72    35     0  33.6  0.627   50  tested_positive
1       1    85    66    29     0  26.6  0.351   31  tested_negative
2       8   183    64     0     0  23.3  0.672   32  tested_positive
3       1    89    66    23    94  28.1  0.167   21  tested_negative
4       0   137    40    35   168  43.1  2.288   33  tested_positive
..    ...   ...   ...   ...   ...   ...    ...  ...              ...
763    10   101    76    48   180  32.9  0.171   63  tested_negative
764     2   122    70    27     0  36.8  0.340   27  tested_negative
765     5   121    72    23   112  26.2  0.245   30  tested_negative
766     1   126    60     0     0  30.1  0.349   47  tested_positive
767     1    93    70    31     0  30.4  0.315   23  tested_negative

[768 rows x 9 columns]

In [6]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df)

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   9.9   9.8  10.0     A       0
3     Mary        N   7.7   8.0   NaN     B       0
4     Jeen        K   9.8   9.1   9.9    A+       1
5      Raj        M   8.9   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0

In [6]:
import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.head())

    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0     Joe        K   9.8  10.0   9.9    A+       1
1  Rajesh        M   8.9   9.1   9.3     A       1
2  Kissan        V   9.9   9.8  10.0     A       0
3    Mary        N   7.7   8.0   NaN     B       0
4    Jeen        K   9.8   9.1   9.9    A+       1

In [7]:
df=pd.read_csv("/content/diabetcsv.csv")
print(df.describe)

<bound method NDFrame.describe of      preg  plas  pres  skin  insu  mass   pedi  age            class
0       6   148    72    35     0  33.6  0.627   50  tested_positive
1       1    85    66    29     0  26.6  0.351   31  tested_negative
2       8   183    64     0     0  23.3  0.672   32  tested_positive
3       1    89    66    23    94  28.1  0.167   21  tested_negative
4       0   137    40    35   168  43.1  2.288   33  tested_positive
..    ...   ...   ...   ...   ...   ...    ...  ...              ...
763    10   101    76    48   180  32.9  0.171   63  tested_negative
764     2   122    70    27     0  36.8  0.340   27  tested_negative
765     5   121    72    23   112  26.2  0.245   30  tested_negative
766     1   126    60     0     0  30.1  0.349   47  tested_positive
767     1    93    70    31     0  30.4  0.315   23  tested_negative

[768 rows x 9 columns]>

In [8]:
df=pd.read_csv("/content/diabetcsv.csv")
print(df.describe().T)

      count        mean         std     min       25%       50%        75%  \
preg  768.0    3.845052    3.369578   0.000   1.00000    3.0000    6.00000
plas  768.0  120.894531   31.972618   0.000  99.00000  117.0000  140.25000
pres  768.0   69.105469   19.355807   0.000  62.00000   72.0000   80.00000
skin  768.0   20.536458   15.952218   0.000   0.00000   23.0000   32.00000
insu  768.0   79.799479  115.244002   0.000   0.00000   30.5000  127.25000
mass  768.0   31.992578    7.884160   0.000  27.30000   32.0000   36.60000
pedi  768.0    0.471876    0.331329   0.078   0.24375    0.3725    0.62625
age   768.0   33.240885   11.760232  21.000  24.00000   29.0000   41.00000

         max
preg   17.00
plas  199.00
pres  122.00
skin   99.00
insu  846.00
mass   67.10
pedi    2.42
age    81.00

In [9]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(17, 7)
17
7

In [11]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.columns)
l1=list(df.columns)
print(l1)

Index(['Names', 'Initials', 'SEM1', 'SEM2', 'SEM3', 'Grade', 'Placed'], dtype='object')
['Names', 'Initials', 'SEM1', 'SEM2', 'SEM3', 'Grade', 'Placed']

In [25]:
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']= None
df2.head(7)
df.isnull().head(7)
print(df2.isnull().sum())
print(df['SEM1'])

Names       0
Initials    0
SEM1        3
SEM2        0
SEM3        1
Grade       0
Placed      0
dtype: int64
0     9.8
1     8.9
2     9.9
3     7.7
4     9.8
5     8.9
6     9.9
7     7.7
8     NaN
9     NaN
10    NaN
11    7.7
12    9.8
13    8.9
14    9.3
15    9.9
16    7.7
Name: SEM1, dtype: float64

In [41]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df2[['SEM1','Names']])
print(df[df.index==1])
print(df[df.index.isin(range(2,5))])
print(df2.loc[3])
print(df2.loc[6:11])
df2.loc[[10,2,7]]
df2.loc[10:15,['Names','Grade']]
df2.iloc[10:14, :3]
df2.loc[:7,["Names"]]
df2.loc[df['Names']=='Rajesh']

    SEM1   Names
0    9.8     Joe
1    8.9  Rajesh
2    7.0  Kissan
3    7.0    Mary
4    7.0    Jeen
5    7.0     Raj
6    9.9  Hassan
7    7.7    Mari
8    NaN    Jess
9    NaN  Rajini
10   NaN   Kiran
11   7.7    Maya
12   9.8   Jolin
13   8.9  Rajesh
14   9.3    Riya
15   9.9    Sana
16   7.7    Mark
    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
1  Rajesh        M   8.9   9.1   9.3     A       1
    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
2  Kissan        V   9.9   9.8  10.0     A       0
3    Mary        N   7.7   8.0   NaN     B       0
4    Jeen        K   9.8   9.1   9.9    A+       1
Names       Mary
Initials       N
SEM1         7.0
SEM2         8.0
SEM3         NaN
Grade          B
Placed         0
Name: 3, dtype: object
     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
1   Rajesh        M   8.9   9.1   9.3     A       1
13  Rajesh        M   8.9   9.1   9.3     A       1

In [43]:
df[df.Grade == 'A']
df[df.SEM2 == 10]

  Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0   Joe        K   9.8  10.0   9.9    A+       1

In [44]:
df.loc[df['SEM1']>9.8,['Names']]

     Names
2   Kissan
6   Hassan
15    Sana

In [51]:
df3=df2.copy()

In [53]:
df3.dropna(inplace=True,axis=1)
print(df3)

     Names Initials  SEM2 Grade  Placed
0      Joe        K  10.0    A+       1
1   Rajesh        M   9.1     A       1
2   Kissan        V   9.8     A       0
3     Mary        N   8.0     B       0
4     Jeen        K   9.1    A+       1
5      Raj        M   9.1     A       1
6   Hassan        V   9.0     A       1
7     Mari        N   8.0     B       1
8     Jess        K   9.1    A+       1
9   Rajini        M   9.1     A       0
10   Kiran        V   9.3     A       0
11    Maya        N   8.0     B       0
12   Jolin        K   9.1    A+       1
13  Rajesh        M   9.1     A       1
14    Riya        M   9.9     A       1
15    Sana        V   9.3     A       0
16    Mark        N   8.0     B       0

In [54]:
df3.dropna(inplace=True, how='all')
print(df3)

     Names Initials  SEM2 Grade  Placed
0      Joe        K  10.0    A+       1
1   Rajesh        M   9.1     A       1
2   Kissan        V   9.8     A       0
3     Mary        N   8.0     B       0
4     Jeen        K   9.1    A+       1
5      Raj        M   9.1     A       1
6   Hassan        V   9.0     A       1
7     Mari        N   8.0     B       1
8     Jess        K   9.1    A+       1
9   Rajini        M   9.1     A       0
10   Kiran        V   9.3     A       0
11    Maya        N   8.0     B       0
12   Jolin        K   9.1    A+       1
13  Rajesh        M   9.1     A       1
14    Riya        M   9.9     A       1
15    Sana        V   9.3     A       0
16    Mark        N   8.0     B       0

In [63]:
mv=df3['SEM2'].mean()
df3=df3.fillna(mv)
print(df3)

     Names Initials  SEM2 Grade  Placed
0      Joe        K  10.0    A+       1
1   Rajesh        M   9.1     A       1
2   Kissan        V   9.8     A       0
3     Mary        N   8.0     B       0
4     Jeen        K   9.1    A+       1
5      Raj        M   9.1     A       1
6   Hassan        V   9.0     A       1
7     Mari        N   8.0     B       1
8     Jess        K   9.1    A+       1
9   Rajini        M   9.1     A       0
10   Kiran        V   9.3     A       0
11    Maya        N   8.0     B       0
12   Jolin        K   9.1    A+       1
13  Rajesh        M   9.1     A       1
14    Riya        M   9.9     A       1
15    Sana        V   9.3     A       0
16    Mark        N   8.0     B       0